baseURL = "https://blog.carroty.app/"
languageCode = "en-gb"
title = "Carroty Blog"
theme = "PaperMod"


[params]
  defaultTheme = "light"
  disableThemeToggle = true
  favicon = true
  hideMeta = false
  hideFooter = true
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = false
  showCodeCopyButtons = true
  disableSpecial1stPost = true
  label.text = "Carroty Blog"
  label.icon = "/images/logo-no-background.png"
  label.iconHeight = 32

[params.profileMode]
  enabled = false

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Carroty"
    url = "https://carroty.app/"
    weight = 1
